name: CI

# Controls when the workflow will run
on:
  push:
    branches:
    - main
    - develop
    - feature/sonarcloud
  pull_request:
    branches: 
    - main
    - develop

  workflow_dispatch:

jobs:
  lint:
    name: lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '>=1.17.0'

      - name: Install dependencies
        run: |
            go version
            go get -u golang.org/x/lint/golint
            go install -v golang.org/x/lint/golint

      - name: Run vet & lint
        run: |
            go vet
            golint -set_exit_status

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.7

  test:
    name: test
    needs: lint

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '>=1.17.0'

      - name: Run testing
        run: go test -v ./pkg/doh

  build:
    name: build
    needs: test

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '>=1.17.0'

      - name: Run build and Test Command
        run: |
          go build .
          ./doh
          ./doh a example.com
          ./doh get example.com
          ./doh a EXaMpLe.com
          ./doh all example.com
          ./doh extensive example.com
